name: Deploy to Amazon ECR

env:
  aws_region: eu-central-1
  ecr_repository: ${{ github.event.repository.name }}
  dockerfile: "Dockerfile"

on:
  pull_request:
    branches:
      - deploy
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Upload image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login_to_ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: public ECR
        env:
          IMAGE_TAG: "${{ github.sha }}"
          ECR_REPOSITORY: ${{ env.ecr_repository }}-pub
          DOCKERFILE: ${{ env.dockerfile }}
          ALIAS: w6x7i9z5
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG -f $DOCKERFILE .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG public.ecr.aws/$ALIAS/$ECR_REPOSITORY:$IMAGE_TAG
          docker push public.ecr.aws/$ALIAS/$ECR_REPOSITORY:$IMAGE_TAG

      # Private ECR part
      # - name: Private ECR
      #   id: build-image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login_to_ecr.outputs.registry }}
      #     ECR_REPOSITORY: ${{ env.ecr_repository }}-pub
      #     IMAGE_TAG: "${{ github.sha }}"
      #     DOCKERFILE: ${{ env.dockerfile }}
      #   run: |
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $DOCKERFILE .
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      #     docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      #     echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
